config/routes.rb
Rails.application.routes.draw do
  
  get "/photos/new",{:controller => "photos", :action =>"new", :as =>"new_photo"}
  post "/photos", {:controller => "photos", :action =>"create", :as =>"photos" }
  
   get "/photos/:id", {:controller => "photos", :action => "show", :as => "photo"}
  
  
  
  
  
  
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/photos_controller.rb
class PhotosController < ApplicationController
    #Create
    def new
        render "new"
    end    
    
    def create
       @var=Photo.new
       @var.caption=params["caption"]
       @var.photo=params["photo"]
       @var.save
       redirect_to "/photos/#{@var.id}"
    end    
    
    #Read
     def show
        @var=Photo.find(params[:id])
        render "show"
     end
    
    
    #Update
    
    
    #Destroy
    
    
    
    
    
    
end        

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Page</h1>

<%= form_tag(photo_path(@var.id), :method => :patch) do %>

    <input name="authenticity_token" value="<%=form_authenticity_token %>" type="hidden">
    
    <label for="caption"> Caption
        <input type="text" id="caption" name="caption" value="<%= @var.caption %>">
    </label>
    <label for="photo"> URL
        <input type="text" id="photo" name="photo" value="<%= @var.photo %>">
    </label>
    <input type="submit">
<% end %>    

app/views/photos/new.html.erb
<h1>new record</h1>

<form method="post" action="/photos">
    <input name="authenticity_token" value="<%=form_authenticity_token %>" type="hidden"></input>
    
    <label for="caption">
        caption: <input type="text" id="caption" name="caption"></input>
    </label>
     <label for="photo">
        photo URL: <input type="text" id="photo" name="photo"></input>
    </label>
    <input type="submit"></input>
    
    
    
    
    
</form>

app/views/photos/show.html.erb
<h1>display model records</h1>
<h1>heyy</h1>
<img src="<%= @var.photo %>">
<p>caption <%= @var.caption %> </p>


<!-- <a href="/photos/<%= @var.id %>/edit">Edit</a> -->